# Generated by Django 4.2.8 on 2024-02-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_categories_name_alter_categories_slug_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество'),
        ),
    ]
